name: Build Mod

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Java 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x ./Toms-Storage-120/gradlew

    - name: Build
      env:
        GRADLE_OPTS: "-Xmx3g -Dorg.gradle.daemon=false"
      run: cd Toms-Storage-120 && ./gradlew build -x test

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Toms-Storage-1.20.1-Forge
        path: Toms-Storage-120/build/libs/*.jar
